mblajek/Memo

app/Models/User.php, app/Utils/Uuid/UuidTrait.php, routes/console.php
standardowy trait HasUuids nadaje uuid'y zaczynające się od timestampa, tak se; poprawiłem
=> FZ-17 fixed uuids to be random, not ordered; added fz:hash and fz:user command

help/api.md
=> opisanie założeń api

app/Exceptions/ApiException.php, app/Exceptions/ApiExceptionTrait.php, app/Exceptions/ApiFatalException.php, app/Exceptions/ApiValidationException.php, app/Exceptions/ExceptionFactory.php, app/Exceptions/ValidationExceptionRenderer.php, app/Http/Controllers/Admin/AdminFacilityController.php, app/Http/Controllers/Admin/AdminUserController.php, app/Http/Controllers/UserController.php, resources/lang/pl_PL/index.json, routes/api.php, tests/Feature/UserAuthenticationTest.php
bad login gives "exception.bad_credentials" and logs out
=> FZ-60 flat error structure

resources/js/components/felte-form/FelteForm.tsx, resources/js/components/felte-form/FelteSubmit.tsx, resources/js/components/ui/Button/Button.tsx, resources/js/components/ui/MemoLoader/MemoLoader.tsx, resources/js/components/ui/form/TextField.tsx, resources/js/components/utils/InitializeTanstackQuery.tsx, resources/js/components/utils/classnames.ts, resources/js/components/utils/index.ts, resources/js/components/utils/lang.ts, resources/js/features/authentication/forms/login/Login.form.tsx, resources/js/features/root/layout/Container.tsx, resources/js/features/root/layout/Footer.tsx, resources/js/features/root/layout/Header.tsx, resources/js/features/root/layout/Main.tsx, resources/js/features/root/layout/Navbar.tsx
Also formatted the touched files, which just removed the spaces from the inside of braces, as agreed.
=> Created getLangFunc() util function for translation. Exported classnames lib as cx to allow easier import.

resources/js/components/ui/Table/TQueryTable.tsx, resources/js/components/ui/Table/style.module.scss, resources/js/features/root/layout/style.module.scss, resources/js/features/root/pages/AdminUsersList.page.tsx
Not sure about this approach but this is a draft of how the display modes of a table could work.
Horizontal scrolling still doesn't work. It is difficult to combine with sticky.
=> FZ-72-FZ-80-table-layout

resources/js/components/felte-form/FelteForm.tsx, resources/js/components/felte-form/FelteSubmit.tsx, resources/js/components/ui/form/TextField.tsx, resources/js/features/root/layout/Header.tsx, resources/js/features/user-panel/PasswordChange.form.tsx, resources/js/features/user-panel/index.ts, resources/lang/pl_PL/forms.json, resources/lang/pl_PL/validation.json
The form is opened in a dialog. The trigger button is temporarily placed in the page header.
=> FZ-56 Created the password change form.

resources/js/components/ui/Table/CellRenderer.tsx
The pull: https://github.com/mblajek/Memo/pull/56
=> Fix for a bad pull (CellRenderer)

resources/js/components/ui/Table/TQueryTable.tsx, resources/js/features/root/pages/AdminUsersList.page.tsx
- Fixed the regression that column filter loses focus while fetching data.
- Fixed the regression that some cells are incorrectly empty or stale.
=> FZ-39 Table fixes

resources/js/components/ui/Table/tquery_filters/ColumnFilterController.tsx, resources/js/components/ui/css_classes.ts, resources/js/components/utils/QueryBarrier.tsx, resources/js/data-access/memo-api/groups/User.ts, resources/js/features/authentication/forms/login/Login.form.tsx, resources/js/features/root/layout/Header.tsx, resources/js/features/user-panel/PasswordChange.form.tsx
- any cleanup
- invalidators extracted to a function
- used function form of Show
=> Minor changes:

.eslintrc.json, resources/js/App.tsx, resources/js/components/utils/InitializeTanstackQuery.tsx, resources/js/data-access/memo-api/groups/Admin.ts, resources/js/data-access/memo-api/groups/System.ts, resources/js/data-access/memo-api/query_utils.ts, resources/js/data-access/memo-api/tquery/tquery.ts, resources/js/data-access/memo-api/types.ts, resources/js/data-access/memo-api/utils.ts, resources/js/features/root/layout/Header.tsx, resources/js/features/root/pages/users_fake_tquery.ts
- Implemented a getUser call based on getUsersList, with 404 generated on the client.
- Added more API types, query keys, backend call functions and invalidators.
=> More infrastructure around querying the backend.

app/Services/User/UpdateUserService.php, resources/js/components/ui/form/index.ts, resources/js/components/ui/form/util.ts, resources/js/data-access/memo-api/groups/Admin.ts, resources/js/data-access/memo-api/groups/User.ts, resources/js/data-access/memo-api/resources/adminUser.resource.ts, resources/js/data-access/memo-api/types.ts, resources/js/features/root/pages/AdminUsersList.page.tsx, resources/js/features/users-edit/UserEdit.form.tsx, resources/js/features/users-edit/index.ts, resources/lang/pl_PL/forms.yml
Nie obejmuje aktualnie edycji placówek ani uprawnień administratora globalnego.
=> FZ-57 Formularz edycji danych użytkownika.

resources/js/components/ui/CopyToClipboard.tsx, resources/js/components/ui/Table/IdColumn.tsx, resources/js/components/ui/Table/TQueryTable.tsx, resources/js/components/ui/Table/index.ts, resources/js/components/ui/Table/table_cells.tsx, resources/js/components/ui/Table/tquery_filters/ColumnFilterController.tsx, resources/js/components/ui/Table/tquery_filters/UuidFilterControl.tsx, resources/js/data-access/memo-api/tquery/types.ts, resources/js/features/root/pages/AdminUsersList.page.tsx, resources/js/features/root/pages/users_fake_tquery.ts, resources/lang/pl_PL/tables.yml
Plus some other minor improvements.
=> FZ-90 Made the id column available for the user, with clipped and copiable id shown, with filtering enabled but no sorting.

resources/js/components/utils/InitializeTanstackQuery.tsx, resources/js/data-access/memo-api/tquery/table.ts, resources/js/data-access/memo-api/tquery/tquery.ts, resources/js/data-access/memo-api/tquery/types.ts, resources/js/features/root/pages/users_fake_tquery.ts
Also better error of general validation errors (outside of forms).
=> Small changes to tquery, to sync with the backend code.

resources/js/components/felte-form/FelteForm.tsx, resources/js/components/felte-form/FelteSubmit.tsx, resources/js/components/felte-form/UnknownValidationMessages.tsx, resources/js/components/felte-form/ValidationMessages.tsx, resources/js/components/felte-form/index.ts, resources/js/components/ui/Capitalize.tsx, resources/js/components/ui/Confirmation.tsx, resources/js/components/ui/Modal/Modal.tsx, resources/js/components/ui/form/Checkbox.tsx, resources/js/components/ui/form/FieldLabel.tsx, resources/js/components/ui/form/SimpleSelect.tsx, resources/js/components/ui/form/TextField.tsx, resources/js/components/ui/form/index.ts, resources/js/features/user-panel/PasswordChange.form.tsx, resources/js/index.tsx, resources/lang/pl_PL/forms.yml
- Better styles here and there.
- Form now supports displaying validation errors that are not bound to any form field (will be useful when form sends multiple requests, e.g. editing user with members).
- Optional cancel button.
- Created a simple select component (wrapping native select).
=> Multiple improvements in forms and utility components.

package-lock.json, package.json, resources/js/components/ui/Table/table_cells.tsx, resources/js/components/ui/Table/tquery_filters/DateTimeFilterControl.tsx, resources/js/components/utils/formatting.ts, resources/js/data-access/memo-api/utils.ts, resources/js/features/root/layout/Header.tsx
The luxon should be much nicer to use when dealing with the calendars and custom datetime formats that we will probably need.
=> Switched all date operations on frontend from native Date to luxon DateTime.

resources/js/components/ui/Table/Pagination.tsx, resources/js/components/ui/Table/TQueryTable.tsx, resources/js/components/ui/Table/TableSearch.tsx, resources/js/components/ui/Table/table_cells.tsx, resources/js/components/ui/Table/tquery_filters/ColumnFilterController.tsx, resources/js/components/ui/Table/tquery_filters/DateFilterControl.tsx, resources/js/components/ui/Table/tquery_filters/DateFilterForDateTimeColumnControl.tsx, resources/js/components/ui/Table/tquery_filters/Decimal0FilterControl.tsx, resources/js/components/ui/Table/tquery_filters/Decimal2FilterControl.tsx, resources/js/components/ui/Table/tquery_filters/UuidFilterControl.tsx
Plus other fixes in table.
The nullability is still not supported in the filters.
=> FZ-39 Added nullable types to tquery.

resources/js/components/ui/form/util.ts, resources/js/features/users-edit/UserEdit.form.tsx
Also sending the hasPassword field in user edit/create form, just in case.
=> FZ-57 Improved field trimming by removing multispaces.

resources/js/components/ui/Table/TableSummary.tsx
summaryTranslation prop is unused
=> Simplify TableSummary

resources/js/components/ui/Modal/Modal.module.scss, resources/js/components/ui/Table/Table.module.scss, resources/js/components/ui/Table/TableColumnVisibilityController.tsx, resources/js/features/not-found/components/NotFound.tsx, resources/js/features/root/components/navbar/NavigationItem.tsx, resources/js/index.scss
- Added shadow to buttons.
- Added blue and underline to links by default.
- Set the select background color to white, which was not the case on some variants of Chrome.
=> Style improvements.

resources/js/features/root/pages/AdminUsersList.page.tsx
(because it's meaningless and also broken)
=> Disable sorting of actions column

resources/js/features/users-edit/UserMembersEdit.tsx
The added facility field was sometimes filled in after deleting a members row.
=> Fixed the user members edit field (hotfix).

resources/js/components/felte-form/FelteForm.tsx, resources/js/features/facility-edit/FacilityForm.tsx, resources/js/features/users-edit/UserEdit.tsx
(except for passwords that are still set autocomplete on <input>
and autcomplete regardless in most browsers)
=> Switch autocomplete=off globally on <form>

resources/js/components/felte-form/FelteForm.tsx, resources/js/components/felte-form/FelteSubmit.tsx, resources/js/components/ui/Capitalize.tsx, resources/js/components/ui/Table/Table.tsx, resources/js/components/ui/Table/TableSearch.tsx, resources/js/components/ui/TranslatedText.tsx, resources/js/components/ui/calendar/TinyCalendar.tsx, resources/js/components/ui/form/FieldLabel.tsx, resources/js/components/ui/form/SimpleSelect.tsx, resources/js/components/utils/AccessBarrier.tsx, resources/js/components/utils/QueryBarrier.tsx, resources/js/components/utils/html_attributes.ts, resources/js/features/facility-edit/FacilityForm.tsx, resources/js/features/root/components/navbar/NavigationItem.tsx, resources/js/features/root/components/navbar/NavigationSection.tsx, resources/js/features/root/pages/Root.page.tsx, resources/js/features/users-edit/UserEdit.tsx
The "local props", i.e. the props directly declared in the component's file, are now always named "props".
=> Unified the naming of props in components where props are merged and split.

.gitignore, .vscode/extensions.json, package-lock.json, package.json, resources/js/components/ui/form/util.test.ts, resources/js/features/facility-edit/FacilityCreateForm.test.tsx, resources/js/features/facility-edit/FacilityCreateForm.tsx, vite.config.ts
Use ```npm test``` to run tests.
=> Add basic test framework

.eslintrc.json, package-lock.json, package.json, resources/js/components/ui/Button/Button.tsx, resources/js/components/ui/calendar/TinyCalendar.tsx, resources/js/features/root/components/header/UserInfo.tsx
Added eslint rule to avoid using the sneaky native button.
=> Removed the kobalte library which was only used for the button wrapper.

resources/js/components/ui/Table/TQueryTable.tsx, resources/js/data-access/memo-api/tquery/types.ts
- Removed the list of columns from data response.
- Added support for the count column, and ensured that it doesn't appear in the table.
=> tquery changes:

app/Http/Resources/DictionaryResource.php, app/Http/Resources/PositionResource.php, app/Models/Dictionary.php, app/Models/Position.php, database/migrations/2023_10_24_194133_dictionaries_add_fields.php
Tried to figure out all the places where this is used, let me know if I missed something.
=> FZ-110 Added properties to dictionaries and positions.

resources/js/components/utils/one_time_effect.ts, resources/js/data-access/memo-api/groups/User.ts, resources/js/features/authentication/pages/Login.page.tsx, resources/js/features/root/components/header/FacilityControl.tsx, resources/js/features/root/pages/AdminFacilitiesList.page.tsx
Store the last login facility on facility change.
=> FZ-84 Created a more solid logic of switching facilities.

database/migrations/2023_11_12_183753_meeting_data.php, help/db_meeting-data.md
Sama migracja na razie, żeby się upewnić, że struktura dobra. W sumie nie wiem czy w ramach FZ-48 mam też dodawać modele czy na to jest osobny ticket.
=> FZ-48 [B] Adding meetings, meeting_attendants and meeting_resources tables

resources/js/components/ui/calendar/ColumnsCalendar.module.scss, resources/js/components/ui/calendar/ColumnsCalendar.tsx, resources/js/components/ui/calendar/FullCalendar.tsx, resources/js/components/ui/calendar/calendar-columns/AllDayArea.module.scss, resources/js/components/ui/calendar/calendar-columns/AllDayArea.tsx, resources/js/components/ui/calendar/calendar-columns/DayHeader.tsx, resources/js/components/ui/calendar/calendar-columns/HoursArea.module.scss, resources/js/components/ui/calendar/calendar-columns/HoursArea.tsx, resources/js/components/ui/calendar/calendar-columns/ResourceHeader.tsx, resources/js/components/ui/calendar/calendar-columns/blocks.tsx, resources/js/components/ui/calendar/calendar-columns/events.tsx, resources/js/components/ui/calendar/calendar-columns/overlaps_calculator.test.ts, resources/js/components/ui/calendar/calendar-columns/overlaps_calculator.ts, resources/js/components/ui/calendar/types.ts, resources/js/components/ui/calendar/util.test.ts, resources/js/components/ui/calendar/util.ts, resources/js/components/ui/symbols.tsx, resources/js/components/utils/html_attributes.ts, resources/js/features/root/MemoTitle.tsx, resources/lang/pl_PL/calendar.yml, tailwind.config.ts
Hardcoded some fake data for testing.
=> FZ-94 Created the columns calendar.

resources/js/components/ui/Table/ColumnName.tsx, resources/js/components/ui/Table/TQueryTable.tsx, resources/js/components/ui/Table/Table.module.scss, resources/js/data-access/memo-api/tquery/table.ts, resources/js/data-access/memo-api/tquery/types.ts
This will allow to inspect the data and configure the columns easier.
=> In DEV mode TQueryTable shows also all the unconfigured columns from schema.

resources/js/components/ui/Table/Header.module.scss, resources/js/components/ui/Table/Table.module.scss, resources/js/data-access/memo-api/attributable.ts, resources/js/data-access/memo-api/attributes.test.ts, resources/js/data-access/memo-api/attributes.ts, resources/js/data-access/memo-api/dictionaries.test.ts, resources/js/data-access/memo-api/dictionaries.ts, resources/js/data-access/memo-api/resources/attribute.resource.ts, resources/js/data-access/memo-api/resources/dictionary.resource.ts, resources/js/data-access/memo-api/resources/name_string.ts, resources/js/dev-pages/AttributesPage.tsx, resources/js/dev-pages/DictionariesPage.tsx, resources/js/dev-pages/util.ts, resources/lang/pl_PL/dictionary.yml
Improvements on the DEV pages for attributes and dictionaries.
=> Changes and improvements in attributes and dictionaries handling.

resources/js/App.tsx, resources/js/FatalError.tsx, resources/js/components/persistence/persistence.ts, resources/js/components/persistence/serialiser.ts, resources/js/components/persistence/storage.test.ts, resources/js/components/persistence/storage.ts, resources/js/components/persistence/version.ts, resources/js/components/ui/FullScreenPre.tsx, resources/js/components/ui/Table/TQueryTable.tsx, resources/js/components/ui/calendar/FullCalendar.tsx, resources/js/components/utils/html_attributes.ts, resources/js/dev-pages/BackdoorRoutes.tsx, resources/js/features/root/layout/Navbar.tsx, resources/js/features/root/pages/Calendar.page.tsx, resources/views/app.blade.php
Improvements in the persistence mechanism: introduced versioning of data to avoid breaking a client.
Added backdoor pages under /dev/ to read and manipulate the local storage, e.g. to help a user recover from a bad local storage persistent state.
=> Persist the state of the calendar page in the local storage.

resources/js/components/ui/SearchInput.tsx, resources/js/components/ui/Table/FilterIconButton.tsx, resources/js/components/ui/Table/TQueryTable.tsx, resources/js/components/ui/Table/TableFiltersClearButton.tsx, resources/js/components/ui/Table/TableSearch.tsx, resources/js/components/ui/Table/index.ts, resources/js/components/ui/Table/tquery_filters/ColumnFilterController.module.scss, resources/js/components/ui/Table/tquery_filters/ColumnFilterController.tsx, resources/js/components/ui/Table/tquery_filters/TextualFilterControl.tsx, resources/js/components/ui/TextInput.tsx, resources/js/components/ui/form/TextField.tsx, resources/js/data-access/memo-api/tquery/table.ts, resources/lang/pl_PL/forms.yml, resources/lang/pl_PL/tables.yml
- Created a button for clearing all the column filters.
- Improved the search inputs (global and textual column).
- Some style fixes and unifications.
=> TQueryTable improvements:

app/Http/Controllers/Facility/ClientTqueryController.php, app/Http/Controllers/Facility/StaffTqueryController.php, app/Tquery/Config/TqDataTypeEnum.php, app/Tquery/Config/TqTableAliasEnum.php, app/Tquery/Engine/TqBuilder.php, app/Tquery/Tables/ClientTquery.php, app/Tquery/Tables/StaffTquery.php, routes/api.php
to jest fragment zadań 117 i 118, bo było ptrzebne, i  to chyba może bezpiecznie trafić na develop
=> FZ-117-118 add base tqueries for clients and staff, fix permissions

resources/js/components/ui/Button.tsx, resources/js/components/ui/Email.tsx, resources/js/components/utils/InitializeTanstackQuery.tsx, resources/js/data-access/memo-api/groups/Admin.ts, resources/js/data-access/memo-api/groups/FacilityClient.ts, resources/js/data-access/memo-api/groups/FacilityMeeting.ts, resources/js/data-access/memo-api/groups/FacilityStaff.ts, resources/js/data-access/memo-api/groups/System.ts, resources/js/data-access/memo-api/groups/User.ts, resources/js/data-access/memo-api/groups/shared.ts, resources/js/data-access/memo-api/invalidator.ts, resources/js/data-access/memo-api/resources/adminUser.resource.ts, resources/js/data-access/memo-api/resources/client.resource.ts, resources/js/data-access/memo-api/resources/resource.ts, resources/js/data-access/memo-api/resources/staff.resource.ts, resources/js/data-access/memo-api/resources/user.resource.ts, resources/js/data-access/memo-api/tquery/filter_utils.test.ts, resources/js/data-access/memo-api/tquery/filter_utils.ts, resources/js/features/authentication/forms/login/Login.form.tsx, resources/js/features/facility-edit/FacilityCreateForm.tsx, resources/js/features/facility-edit/FacilityEditForm.tsx, resources/js/features/meeting/MeetingCreateForm.tsx, resources/js/features/meeting/MeetingViewEditForm.tsx, resources/js/features/root/components/header/FacilityControl.tsx, resources/js/features/root/components/header/UserInfo.tsx, resources/js/features/user-edit/UserCreateForm.tsx, resources/js/features/user-edit/UserEditForm.tsx, resources/js/features/user-panel/PasswordChange.form.tsx
- Created API for staff and client endpoints.
- Changed query keys to better reflect the real data structure.
- Refactored the invalidator.
=> API-related changes:

app/Exceptions/ExceptionFactory.php, app/Exceptions/Handler.php, app/Http/Kernel.php, app/Models/Facility.php, composer.lock, resources/lang/pl_PL/index.yml, routes/api.php
composer update
konfiguracja throtlingu, złapanie exception'a, throtling dla login
zablokowanie kolejnych słów jako url placówki :D
=> Fz 131 - composer update, throtling

package-lock.json, resources/js/components/ui/Table/table_cells.tsx, resources/js/components/ui/calendar/FullCalendar.tsx, resources/js/components/ui/calendar/calendar-columns/events.tsx, resources/js/components/utils/date_formatting.tsx, resources/js/data-access/memo-api/attributes.ts, resources/js/data-access/memo-api/dictionaries.ts, resources/js/data-access/memo-api/resources/meeting.resource.ts, resources/js/data-access/memo-api/tquery/calendar.ts, resources/js/dev-pages/AttributesPage.tsx, resources/js/dev-pages/DictionariesPage.tsx, resources/js/dev-pages/util.ts, resources/js/features/facility-users/CreatedByInfo.tsx, resources/js/features/facility-users/UserDetailsHeader.tsx, resources/js/features/facility-users/UserLink.tsx, resources/js/features/facility-users/UserMeetingsTables.tsx, resources/js/features/meeting/MeetingAttendantsFields.tsx, resources/js/features/meeting/MeetingCreateForm.tsx, resources/js/features/meeting/MeetingForm.tsx, resources/js/features/meeting/MeetingViewEditForm.tsx, resources/js/features/meeting/attendance_status_info.tsx, resources/js/features/meeting/meeting_tables.tsx, resources/js/features/root/pages/Calendar.page.tsx, resources/js/features/root/pages/ClientDetails.page.tsx, resources/js/features/root/pages/StaffDetails.page.tsx, resources/lang/pl_PL/dictionary.yml, resources/lang/pl_PL/models.yml, resources/lang/pl_PL/tables.yml, resources/lang/pl_PL/validation.yml
- Changed the meeting tabes on staff/client details to use the attendants tquery.
- Updated the UI for attendance statuses to support the new statuses system.
- Various UI updates related to meetings.
The backend changes are from other PRs, no need to review.
=> Changes related mostly to meeting attendants:

app/Http/Controllers/Facility/MeetingController.php, app/Services/Meeting/MeetingService.php
Ostatecznie stwierdziłem, że przy zachowaniu jak PUT do arrayów, nie chce mi się sprawdzać obiektu po obiekcie.
Jeśli to konieczne to doimplementuję, ale nie jestem pewien czy warto.
=> FZ-125 [B] Meetings patch

app/Http/Controllers/ApiController.php, package-lock.json, resources/js/features/meeting/meeting_time_controller.tsx
=> Fixed editing all day meetings in the calendar.

resources/js/components/ui/LoadingPane.tsx, resources/js/components/ui/title.tsx
- Fixed the performance when creating many tooltips.
- Fixed an issue where CPU usage was high all the time. On some machines it was even very high if the page was zoomed in.
=> Performance hotfixes
